import { Sparkles, BarChart3, List, MessageSquare, Link, BookOpen, Settings, Bot, PartyPopper } from 'lucide-react';

const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    title: 'ברוכה הבאה למערכת! 🌸',
    content: 'המערכת מנהלת את כל התקשורת עם הלקוחות שלך — מהפנייה הראשונה ועד לתור.\nהבוט בוואטסאפ עובד אוטומטית, ואת צריכה רק לפקח ולעדכן.',
    icon: Sparkles,
    iconColor: 'text-primary',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
    canPractice: false,
  },
  {
    id: 'dashboard',
    title: 'לבדוק סטטוס לקוח',
    content: 'בדאשבורד את רואה כמה פניות יש בכל סטטוס.\nלחצי על אחת מההתראות (לידים חדשים / הודעות לבדיקה) כדי לעבור ישירות לפניות הרלוונטיות.',
    tip: 'הכרטיסים הכתומים והאדומים דורשים תשומת לב — לחצי עליהם!',
    icon: BarChart3,
    iconColor: 'text-emerald-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="alert-cards"]',
    navigateTo: '/Dashboard',
    canPractice: true,
    practiceLabel: 'לחצי על התראה 🎯',
  },
  {
    id: 'requests',
    title: 'להבין סטטוסים ופניות',
    content: 'כל פנייה עוברת דרך שלבים:\nליד חדש → שולם → שאלון → נקבע תור → הושלם.\n\nהבוט מטפל אוטומטית ברוב המעברים. את יכולה לשנות סטטוס ידנית או ללחוץ על פנייה לפרטים.',
    tip: 'לחצי על שם הלקוח כדי לראות את כל הפרטים והיסטוריית הטיפול.',
    icon: List,
    iconColor: 'text-blue-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="requests-table"]',
    navigateTo: '/ServiceRequests',
    canPractice: true,
    practiceLabel: 'פתחי פנייה 🎯',
  },
  {
    id: 'bot-content',
    title: 'לעדכן הודעות הבוט',
    content: 'כאן יושבים כל הטקסטים שהבוט שולח ללקוחות.\nאת יכולה לערוך את הנוסח של כל הודעה.',
    tip: '⚠️ חשוב: לא לשנות את ה-key ולא למחוק placeholder כמו {שם} או {קישור} — הם מוחלפים אוטומטית.',
    icon: MessageSquare,
    iconColor: 'text-violet-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="bot-content-table"]',
    navigateTo: '/BotContent',
    canPractice: true,
    practiceLabel: 'ערכי הודעה 🎯',
  },
  {
    id: 'service-content',
    title: 'לעדכן קישורים וקבצים',
    content: 'כאן יושבים כל הקישורים — תשלום, שאלון, הסכם, יומן.\nכשמשהו משתנה (למשל קישור תשלום חדש), את מעדכנת כאן ולא בהודעות.',
    tip: 'הפרדה ברורה: BotContent = טקסטים, ServiceContent = קישורים.',
    icon: Link,
    iconColor: 'text-orange-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="service-content-table"]',
    navigateTo: '/ServiceContent',
    canPractice: true,
    practiceLabel: 'ערכי קישור 🎯',
  },
  {
    id: 'lectures',
    title: 'קטלוג הרצאות',
    content: 'כאן מנהלים את ההרצאות — שם, סרטון, PDF, מחיר.\nהבוט שולף מכאן אוטומטית את החומרים ללקוח.',
    tip: 'אפשר להוסיף הרצאה בודדת, סדרה, או סדנה.',
    icon: BookOpen,
    iconColor: 'text-purple-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="lectures-table"]',
    navigateTo: '/Lectures',
    canPractice: true,
    practiceLabel: 'הוסיפי הרצאה 🎯',
  },
  {
    id: 'settings',
    title: 'הגדרות מערכת',
    content: 'כאן מפעילים/מכבים את הבוט, מגדירים טלפונים לבדיקה, ומנהלים הגדרות כלליות.',
    tip: 'כשרוצים לבדוק את הבוט בלי לשלוח ללקוחות אמיתיים — מכבים את הבוט ומוסיפים טלפון לבדיקה.',
    icon: Settings,
    iconColor: 'text-gray-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="system-settings"]',
    navigateTo: '/SystemSettings',
    canPractice: true,
    practiceLabel: 'בדקי הפעלת בוט 🎯',
  },
  {
    id: 'agent',
    title: 'ההנחיות של הבוט',
    content: 'הנחיות הבוט נמצאות ב-Base44 ← Agents ← dr_adri_bot.\nשם תוכלי לראות את כל ההגיון שלו — מתי הוא שולח מה ובאיזה סדר.',
    tip: '⚠️ לא לשנות בלי תיאום עם המפתחת.',
    icon: Bot,
    iconColor: 'text-cyan-600',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
    canPractice: false,
  },
  {
    id: 'finish',
    title: 'את מוכנה! 🌷',
    content: 'לכל שאלה או בעיה — פני לעינת.\nכפתור ❓ בתפריט תמיד יחזיר את המדריך הזה.',
    icon: PartyPopper,
    iconColor: 'text-pink-500',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
    canPractice: false,
  },
];

export default TUTORIAL_STEPS;